name: Build Lenis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Lenis
        run: pnpm build

      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: lenis-build
          path: ./dist/
